<?php

/**
 * @file
 * This module enables form_ajax login.
 */

use Drupal\Core\Form\FormBuilderInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 */
function form_ajax_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  $form['status_messages'] = [
    '#type' => 'status_messages',
    '#weight' => -10,
  ];

  $form['actions']['submit']['#ajax'] = [
    'callback' => 'form_ajax_user_login_form_callback',
    'event' => 'click',
    'progress' => [
      'type' => 'none',
    ],
    'options' => [
      'query' => [
        FormBuilderInterface::AJAX_FORM_REQUEST => TRUE,
      ],
    ],
  ];
}

/**
 * Callback to check for a valid form.
 */
function form_ajax_user_login_form_callback(array &$form, FormStateInterface $form_state) {
  $messenger = \Drupal::messenger();

  if ($form_state->hasAnyErrors()) {
    $messenger->addError(t('Incorrect login and/or password!'), $form);
  }
  else {
    $messenger->addMessage(t('Hello, <strong>@name</strong>! To see the website as a registered user go to <a href=":front">this link</a>.', ['@name' => $form_state->getValue('name'), ':front' => Url::fromRoute('front')]));
    $form_state->disableRedirect();
    $form['name']['#access'] = FALSE;
    $form['pass']['#access'] = FALSE;
    $form['actions']['submit']['#access'] = FALSE;
  }
  return $form;
}
