<?php

/**
 * @file
 * Contains hooks for the message output module.
 */

use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_user_login().
 */
function discount_code_user_login(UserInterface $account) {
  $current_route = \Drupal::routeMatch()->getRouteName();
  $destination = \Drupal::request()->query->get('destination');
  if ($destination && $destination != '/user/login') {
    return;
  }

  if (!in_array($current_route, ['user.reset', 'user.reset.login'])) {
    // Redirect user on login with message.
    $messenger = \Drupal::messenger();
    $message = \Drupal::config('discount_code.settings')
      ->get('message');

    $homeResponse = new RedirectResponse(URL::fromUserInput('/')->toString());
    $homeResponse->send();

    $messenger->addMessage(t($message));
  }
}
