<?php

/**
 * @file
 * Contains hooks for the message output module.
 */

/**
 * Implements hook_page_attachments().
 */
function modal_form_page_attachments(array &$attachments) {
  // Attach library.
  $attachments['#attached']['library'][] = 'modal_form/modal_form';
  $attachments['#attached']['drupalSettings']['modal_form'] = \Drupal::config('modal_form.settings')->get();
}

/**
 * Implements hook_theme_registry_alter().
 */
function modal_form_theme_registry_alter(&$theme_registry) {
  $theme_registry['status_messages']['path'] = drupal_get_path('module', 'modal_form') . '/templates';
  $theme_registry['status_messages']['template'] = 'modal_form';
}
